### ISSUE TITLE
error in torchbiggraph\converters\importers.py

### ISSUE THREAD

**Issue by JagerLee** [facebookresearch/PyTorch-BigGraph#230]
## Observed Results

  * File "e:\anaconda3\lib\site-packages\torchbiggraph\converters\importers.py", line 68, in read
    words[self.weight_col] if self.weight_word is not None else None
AttributeError: 'TSVEdgelistReader' object has no attribute 'weight_word'

![111](https://user-images.githubusercontent.com/35551187/128847244-a5b680d9-8fdd-4db8-ad76-40304c39a53f.png)

## Expected Results

  self.weight_word ---> self.weight_col

**Comment by lw** [comment]
Thanks for reporting it! This was introduced in https://github.com/facebookresearch/PyTorch-BigGraph/commit/b590de4c61fe7185827e44ad41ef21ddcd8239a8, @adamlerer could you fix it?

**Comment by tmarkovich** [comment]
PR 229 should fix it

**Comment by jared-ott** [comment]
The next issue is that the yield returns 4 objects, but line 131 is expecting 3 objects.

**Comment by lw** [comment]
> The next issue is that the yield returns 4 objects, but line 131 is expecting 3 objects.

@adamlerer Could you take a look?

**Comment by derenrich** [comment]
looks like the bug isn't quite fixed. the next line also has a bad reference to `weight_word`

https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/converters/importers.py#L69

**Comment by tmarkovich** [comment]
@adamlerer Should we close this?

**Comment by rkindi** [comment]
I think this looks safe to close
